server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telemed
    driver-class-name: org.postgresql.Driver
    username: "${DB_USER:}"
    password: "${DB_PASSWORD:}"

  cache:
    type: simple

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
openai:
  api-key: "${OPENAI_API_KEY:}"
#jwt:
#  private-key: classpath:keys/private.pem
#  public-key: classpath:keys/public.pem

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.telemed.backend: DEBUG

  mail:
    host: smtp.gmail.com
    port: 587
    username: "${MAIL_USER:}"
    password: "${MAIL_PASSWORD:}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000




twilio:
  account-sid: "${TWILIO_ACCOUNT_SID:}"
  auth-token: "${TWILIO_AUTH_TOKEN:}"
  phone-number: "${TWILIO_PHONE_NUMBER:}"

cache:
  jwtBlacklist:
    ttl: 3600
